openapi: 3.0.2
info:
  title: Keep actions users API
  description: Rest API powering https://platform.keephq.dev and friends 🏄‍♀️
  version: 0.24.5
tags:
- name: users
paths:
  /auth/users:
    get:
      tags:
      - users
      summary: Get Users
      description: Get all users
      operationId: get_users_auth_users_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
                title: Response Get Users Auth Users Get
      security:
      - API Key: []
      - HTTPBasic: []
      - OAuth2PasswordBearer: []
    post:
      tags:
      - users
      summary: Create User
      description: Create a user
      operationId: create_user_auth_users_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key: []
      - HTTPBasic: []
      - OAuth2PasswordBearer: []
  /auth/users/{user_email}:
    put:
      tags:
      - users
      summary: Update User
      description: Update a user
      operationId: update_user_auth_users__user_email__put
      parameters:
      - required: true
        schema:
          type: string
          title: User Email
        name: user_email
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key: []
      - HTTPBasic: []
      - OAuth2PasswordBearer: []
    delete:
      tags:
      - users
      summary: Delete User
      description: Delete a user
      operationId: delete_user_auth_users__user_email__delete
      parameters:
      - required: true
        schema:
          type: string
          title: User Email
        name: user_email
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key: []
      - HTTPBasic: []
      - OAuth2PasswordBearer: []
components:
  schemas:
    User:
      properties:
        email:
          type: string
          title: Email
        name:
          type: string
          title: Name
        role:
          type: string
          title: Role
        picture:
          type: string
          title: Picture
        created_at:
          type: string
          title: Created At
        last_login:
          type: string
          title: Last Login
        ldap:
          type: boolean
          title: Ldap
          default: false
        groups:
          items:
            $ref: '#/components/schemas/Group'
          type: array
          title: Groups
          default: []
      type: object
      required:
      - email
      - name
      - created_at
      title: User
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    CreateUserRequest:
      properties:
        username:
          type: string
          title: Username
        name:
          type: string
          title: Name
        password:
          type: string
          title: Password
        role:
          type: string
          title: Role
        groups:
          items:
            type: string
          type: array
          title: Groups
      type: object
      required:
      - username
      title: CreateUserRequest
    UpdateUserRequest:
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
        role:
          type: string
          title: Role
        groups:
          items:
            type: string
          type: array
          title: Groups
      type: object
      title: UpdateUserRequest
    Group:
      properties:
        id:
          type: string
          title: Id
        name:
          type: string
          title: Name
        roles:
          items:
            type: string
          type: array
          title: Roles
          default: []
        members:
          items:
            type: string
          type: array
          title: Members
          default: []
        memberCount:
          type: integer
          title: Membercount
          default: 0
      type: object
      required:
      - id
      - name
      title: Group
  securitySchemes:
    API Key:
      type: apiKey
      in: header
      name: X-API-KEY
    HTTPBasic:
      type: http
      scheme: basic
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: token
